#ifndef CGAL_REGION_GROWING_H
#define CGAL_REGION_GROWING_H

#include <CGAL/Region_growing/Generalized_region_growing.h>
#include <CGAL/Region_growing/Region_growing_with_points/Generalized_region_growing_points_traits_2.h>
#include <CGAL/Region_growing/Region_growing_with_points/Generalized_region_growing_points_connectivity_2.h>
#include <CGAL/Region_growing/Region_growing_with_points/Generalized_region_growing_points_conditions_2.h>

#endif